### ISSUE TITLE
Building for older os

### ISSUE THREAD

**Issue by mercurial-moon** [lukaslueg/railroad_dsl#10]
Hi,

I try to build `railroad_dsl` with an older toolchain (1.77)  for making it work Windows 7.
My build system has a newer OS however I want to run the built exe on older os like Windows 7.

While building I get error like

> error[E0658]: use of unstable library feature 'lazy_cell'
> on render.rs line 67
> 67 | static USVG_OPTS: std::sync::LazyLock<resvg::usvg::Options> = std::sync::LazyLock::new(|| {

**Comment by lukaslueg** [comment]
The crate doesn't have a MSRV, the most recent Rust-compiler is assumed to be available. Windows7 itself is EOL, so this is a tough ask anyway.

The most simple way forward would be to make the `railroad/resvg`-feature optional, which allows this crate to compile on previous compilers, yet losing the rendering-ability. Can you submit a PR for that?

**Comment by mercurial-moon** [comment]
Hi, not well versed in rust... In the end had to download an older rust environment, and got the app built using that.
